apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: app-deployment-template-1.4.2
  namespace: cluster-test
spec:
  serviceAccountName: default
  templates:
  - name: app-deployment
    container:
      image: alpine:3.7
      command: [echo,"deployment ...."]