apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: app-rendering-template-1.4.2
  namespace: argocd
spec:
  serviceAccountName: default
  templates:
  - name: app-rendering
    container:
      image: alpine:3.7
      command: [echo,"rendering ...."]