apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: diff-project-same-namespace
    server: https://kubernetes.default.svc
  project: project-1
  source:
    path: diff-project-same-ns/app1/ms
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
