apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: same-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app1/ms
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
