apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-versions-apps
  namespace: cluster-test
spec:
  destination:
    namespace: cluster-test
    server: https://kubernetes.default.svc
  project: cluster-test
  source:
    path: cluster-test/team1_workflows
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    directory:
      include: 'version_*.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
