apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-versions-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster
  source:
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    directory:
      include: 'cluster-test/team1_workflows/version_*.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
