apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-workflows-1.3.0
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: /cluster-test/team1_workflows/1.3.0/
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    recursive: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
