apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-workflows-1.4.2
  namespace: cluster-test
spec:
  destination:
    namespace: cluster-test
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: cluster-test/team1_workflows/1.4.2
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    recursive: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true