apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-components
  namespace: cluster-test
spec:
  destination:
    namespace: cluster-test
    server: https://kubernetes.default.svc
  project: cluster-test
  source:
    path: cluster-test
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    directory:
      include: '*_workflows_versions_apps.yaml'
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

