apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-components
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: cluster-test/workflows_app_of_apps.yaml
    repoURL: https://github.com/shurikg/test-argocd.git
    targetRevision: main
    directory:
      include: 'cluster-test/*/*_versions_apps.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

