apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-versions-apps
  namespace: cluster-test
spec:
  destination:
    namespace: cluster-test
    server: https://kubernetes.default.svc
  project: cluster
  source:
    repoURL: https://github.com/shurikg/test-argocd.git
    path: cluster-test/team2_workflows
    targetRevision: main
    directory:
      include: 'version_*.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
