apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: app-deployment-template-1.3.0
  namespace: argocd
spec:
  serviceAccountName: default
  templates:
  - name: app-deployment
    container:
      image: alpine:3.7
      command: [echo,"deployment ...."]