apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: load-configuration-template-1.3.0
  namespace: argocd
spec:
  serviceAccountName: default
  templates:
  - name: load-configuration
    container:
      image: alpine:3.7
      command: [echo,"sssss"]
