apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: report-template-1.3.0
  namespace: cluster-test
spec:
  serviceAccountName: default
  templates:
  - name: report
    container:
      image: alpine:3.7
      command: [echo,"report ...."]